# permissions for end users to edit sensorclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sensorclient-editor-role
rules:
- apiGroups:
  - sensor.cli
  resources:
  - sensorclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sensor.cli
  resources:
  - sensorclients/status
  verbs:
  - get
