# permissions for end users to view sensorclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sensorclient-viewer-role
rules:
- apiGroups:
  - sensor.cli
  resources:
  - sensorclients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sensor.cli
  resources:
  - sensorclients/status
  verbs:
  - get
